apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: default
data:
  db_driver: Y29tLm15c3FsLmNqLmpkYmMuRHJpdmVy #com.mysql.cj.jdbc.Driver
  db_password: c2pkMDIxOSE= #sjd0219!
  db_url: amRiYzpteXNxbDovL215c3FsOjMzMDYvdGVzdF9kYg== #jdbc:mysql://mysql:3306/test_db
  db_username: cm9vdA== #root
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: email-credentials
  namespace: default
data:
  username: Z3Jvb21faGlkZUBuYXZlci5jb20= #groom_hide@naver.com
  password: Z3Jvb21faGlkZTEyMw== #groom_hide123
type: Opaque